addons:
  apt:
    packages:
    - libcurl4-openssl-dev

language: php
php:
  - 7.0
  - 5.6

before_script:
  - composer self-update
  - composer install

script: vendor/bin/phing test -Donly.units=true
